src/TicketManagement.WebApplication/Models/Event/CreateEventViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TicketManagement.WebApplication.Models.Event
{
    public class CreateEventViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [Display(Name = "Name")]
        public string Name { get; set; } = string.Empty;

        [Required(ErrorMessage = "Description is required")]
        [Display(Name = "Description")]
        public string Description { get; set; } = string.Empty;

        public string Layout { get; set; } = string.Empty;

        public string Venue { get; set; } = string.Empty;

        [Display(Name = "Layout")]
        public SelectList? Layouts { get; set; }

        [Display(Name = "Venue")]
        public SelectList? Venues { get; set; }

        [Display(Name = "Start date")]
        public DateTime StartDate { get; set; }

        [Display(Name = "End date")]
        public DateTime EndDate { get; set; }

        [Display(Name = "Image link")]
        public string? ImageUrl { get; set; }

        public bool Published { get; set; }
    }
}

src/TicketManagement.WebApplication/Models/Event/CreatePurchaseViewModel.cs
using TicketManagement.WebApplication.Models.Area;

namespace TicketManagement.WebApplication.Models.Event
{
    public class CreatePurchaseViewModel
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string? UserId { get; set; }
        public List<int> SeatIds { get; set; } = new List<int>();
    }
}

src/TicketManagement.WebApplication/Models/Event/EditEventViewModel.cs
using TicketManagement.WebApplication.Models.EventArea;

namespace TicketManagement.WebApplication.Models.Event
{
    public class EditEventViewModel
    {
        public CreateEventViewModel? Event { get; set; }

        public List<EventAreaViewModel> Areas { get; set; } = new List<EventAreaViewModel>();
    }
}

src/TicketManagement.WebApplication/Models/Event/EventViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TicketManagement.WebApplication.Models.Event
{
    public class EventViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [Display(Name = "Name")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Description is required")]
        [Display(Name = "Description")]
        public string? Description { get; set; }

        public int LayoutId { get; set; }

        [Display(Name = "Start date")]
        public DateTime StartDate { get; set; } = DateTime.Now;

        [Display(Name = "End date")]
        public DateTime EndDate { get; set; } = DateTime.Now;

        [Display(Name = "Image link")]
        public string? ImageUrl { get; set; }

        [Display(Name = "Published")]
        public bool Published { get; set; }
    }
}

src/TicketManagement.WebApplication/Models/Event/LayoutViewModel.cs
namespace TicketManagement.WebApplication.Models.Event
{
    public class LayoutViewModel
    {
        public int Id { get; set; }

        public int VenueId { get; set; }

        public string? Description { get; set; }
    }
}

src/TicketManagement.WebApplication/Models/Event/ModelExtensions.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using TicketManagement.Core.Clients.EventApi.Models;
using TicketManagement.Core.Clients.VenueApi.Models;

namespace TicketManagement.WebApplication.Models.Event
{
    public static class ModelExtensions
    {
        public static CreateEventViewModel Create(this EventModel @event, List<LayoutModel> layouts, int layoutId, List<VenueModel> venues, int venueId)
        {
            return new CreateEventViewModel
            {
                Id = @event.Id,
                Name = @event.Name!,
                Description = @event.Description!,
                StartDate = @event.StartDate,
                EndDate = @event.EndDate,
                ImageUrl = @event.ImageUrl,
                Layout = layoutId.ToString(),
                Venue = venueId.ToString(),
                Layouts = new SelectList(layouts, "Id", "Description"),
                Venues = new SelectList(venues, "Id", "Description"),
                Published = @event.Published,
            };
        }
    }
}

src/TicketManagement.WebApplication/Models/Event/VenueViewModel.cs
namespace TicketManagement.WebApplication.Models.Event
{
    public class VenueViewModel
    {
        public int Id { get; set; }

        public string? Description { get; set; }

        public string? Address { get; set; }

        public string? Phone { get; set; }
    }
}

src/TicketManagement.WebApplication/Controllers/EventController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TicketManagement.Core.Clients.EventApi;
using TicketManagement.Core.Clients.EventApi.Models;
using TicketManagement.Core.Clients.VenueApi;
using TicketManagement.Core.Models;
using TicketManagement.WebApplication.Extensions;
using TicketManagement.WebApplication.Filters;
using TicketManagement.WebApplication.Models.Event;
using TicketManagement.WebApplication.Models.EventArea;
using TicketManagement.WebApplication.Services;

namespace TicketManagement.WebApplication.Controllers
{
    [AuthorizeRoles(Roles.EventManager)]
    [RedirectFilter]
    public class EventController : BaseController
    {
        private readonly IEventClient _eventClient;
        private readonly IEventAreaClient _eventAreaClient;
        private readonly IMapper _mapper;

        public EventController(
            IEventClient eventClient,
            IEventAreaClient eventAreaClient,
            ITokenService tokenService,
            IMapper mapper)
            : base(tokenService)
        {
            _eventClient = eventClient ?? throw new ArgumentNullException(nameof(eventClient));
            _eventAreaClient = eventAreaClient ?? throw new ArgumentNullException(nameof(eventAreaClient));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var events = await _eventClient.GetPublishedEventsAsync(TokenService.GetToken());

            var eventsVM = events
                .Select(e => _mapper.Map<EventViewModel>(e))
                .ToList();

            return View(eventsVM);
        }

        [HttpGet]
        public async Task<IActionResult> NotPublishedEvents()
        {
            var events = await _eventClient.GetNotPublishedEventsAsync(TokenService.GetToken());

            var eventsVM = events
                .Select(e => _mapper.Map<EventViewModel>(e))
                .ToList();

            return View(eventsVM);
        }

        [HttpGet]
        public async Task<PartialViewResult> PartialLayoutList(int venueId, [FromServices] IVenueClient venueClient)
        {
            var layouts = await venueClient.GetLayoutsByVenueIdAsync(venueId, TokenService.GetToken());

            var layoutsVM = layouts
                .Select(l => _mapper.Map<LayoutViewModel>(l))
                .ToList();

            return PartialView(layoutsVM);
        }

        [HttpGet]
        public async Task<IActionResult> CreateEvent([FromServices] IVenueClient venueClient)
        {
            var venues = await venueClient.GetAllAsync(TokenService.GetToken());

            var venuesVM = venues
                .Select(v => _mapper.Map<VenueViewModel>(v))
                .ToList();

            var layouts = await venueClient.GetLayoutsByVenueIdAsync(venues.First().Id, TokenService.GetToken());

            var layoutsVM = layouts
                .Select(l => _mapper.Map<LayoutViewModel>(l))
                .ToList();

            var model = new CreateEventViewModel
            {
                Layouts = new SelectList(layoutsVM, "Id", "Description"),
                Venues = new SelectList(venuesVM, "Id", "Description"),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateEvent(CreateEventViewModel createModel)
        {
            var @event = _mapper.Map<EventModel>(createModel);

            @event.StartDate = User.GetUtcTime(@event.StartDate);
            @event.EndDate = User.GetUtcTime(@event.EndDate);

            var id = await _eventClient.CreateAsync(@event, TokenService.GetToken());

            return RedirectToAction(nameof(EditEvent), new { id = id });
        }

        [HttpGet]
        public async Task<IActionResult> EditEvent(int id,
            [FromServices] ILayoutClient layoutClient,
            [FromServices] IVenueClient venueClient)
        {
            var @event = await _eventClient.GetByIdAsync(id, TokenService.GetToken());

            var venues = await venueClient.GetAllAsync(TokenService.GetToken());

            var layouts = await layoutClient.GetAllAsync(TokenService.GetToken());

            var venuesVM = venues
                .Select(v => _mapper.Map<VenueViewModel>(v))
                .ToList();

            var layoutsVM = layouts
                .Select(l => _mapper.Map<LayoutViewModel>(l))
                .ToList();

            var selectedLayout = layoutsVM.First(l => l.Id == @event.LayoutId);
            var selectedVenue = venuesVM.First(v => v.Id == selectedLayout.VenueId);

            var eventVM = @event.Create(layouts.Where(l => l.VenueId == selectedVenue.Id).ToList(), selectedLayout.Id, venues, selectedVenue.Id);

            var areas = await _eventClient.GetAreasByEventIdAsync(id, TokenService.GetToken());

            var areasVM = areas
                .Select(a => _mapper.Map<EventAreaViewModel>(a))
                .ToList();

            var editEventVM = new EditEventViewModel
            {
                Event = eventVM,
                Areas = areasVM,
            };

            return eventVM.Published
                ? View("EditPublishedEvent", editEventVM)
                : View("EditNotPublishedEvent", editEventVM);
        }

        [HttpPost]
        public async Task<IActionResult> EditNotPublishedEvent(EditEventViewModel model)
        {
            var @event = _mapper.Map<EventModel>(model.Event);

            @event.StartDate = User.GetUtcTime(@event.StartDate);
            @event.EndDate = User.GetUtcTime(@event.EndDate);

            await _eventClient.UpdateAsync(@event, TokenService.GetToken());

            foreach (var item in model.Areas)
            {
                await _eventAreaClient.UpdatePriceAsync(item.Id, item.Price, TokenService.GetToken());
            }

            return RedirectToAction(nameof(PurchaseController.PurchaseSeats), nameof(PurchaseController), new { id = @event.Id });
        }

        [HttpPost]
        public async Task<IActionResult> EditPublishedEvent(EditEventViewModel model)
        {
            var @event = _mapper.Map<EventModel>(model.Event);

            @event.StartDate = User.GetUtcTime(@event.StartDate);
            @event.EndDate = User.GetUtcTime(@event.EndDate);

            await _eventClient.UpdateAsync(@event, TokenService.GetToken());

            return RedirectToAction(nameof(EditEvent), new { id = @event.Id });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteEvent(int id, [FromServices] IWebHostEnvironment enviroment)
        {
            var @event = await _eventClient.GetByIdAsync(id, TokenService.GetToken());

            var imagePath = Path.Combine(enviroment.WebRootPath, $"{@event!.ImageUrl}");

            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }

            await _eventClient.DeleteAsync(id, TokenService.GetToken());

            return RedirectToAction(nameof(Index));
        }
    }
}

src/TicketManagement.WebApplication/Controllers/PurchaseController.cs
using System.Security.Claims;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TicketManagement.Core.Clients.EventApi;
using TicketManagement.Core.Clients.EventApi.Models;
using TicketManagement.Core.Clients.PurchaseApi;
using TicketManagement.Core.Clients.PurchaseApi.Models;
using TicketManagement.Core.Clients.VenueApi;
using TicketManagement.Core.Models;
using TicketManagement.WebApplication.Models.Event;
using TicketManagement.WebApplication.Models.EventArea;
using TicketManagement.WebApplication.Models.EventSeat;
using TicketManagement.WebApplication.Models.Purchase;
using TicketManagement.WebApplication.Services;

namespace TicketManagement.WebApplication.Controllers
{
    public class PurchaseController : BaseController
    {
        private readonly IEventClient _eventClient;
        private readonly IPurchaseClient _purchaseClient;
        private readonly IEventAreaClient _eventAreaClient;
        private readonly IEventSeatClient _eventSeatClient;
        private readonly IMapper _mapper;

        public PurchaseController(
            IEventClient eventClient,
            IPurchaseClient purchaseClient,
            IEventAreaClient eventAreaClient,
            IEventSeatClient eventSeatClient,
            ITokenService tokenService,
            IMapper mapper)
            : base(tokenService)
        {
            _purchaseClient = purchaseClient ?? throw new ArgumentNullException(nameof(purchaseClient));
            _eventAreaClient = eventAreaClient ?? throw new ArgumentNullException(nameof(eventAreaClient));
            _eventClient = eventClient ?? throw new ArgumentNullException(nameof(eventClient));
            _eventSeatClient = eventSeatClient ?? throw new ArgumentNullException(nameof(eventSeatClient));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        [AuthorizeRoles(Roles.EventManager, Roles.User)]
        public async Task<IActionResult> PurchaseSeats(int id)
        {
            var @event = await _eventClient.GetByIdAsync(id, TokenService.GetToken());

            var eventVM = _mapper.Map<PurchaseSeatsViewModel>(@event);

            var areas = await _eventClient.GetAreasByEventIdAsync(id, TokenService.GetToken());

            foreach (var area in areas)
            {
                var areaVM = _mapper.Map<EventAreaViewModel>(area);

                var seats = await _eventAreaClient.GetSeatsByAreaIdAsync(areaVM.Id, TokenService.GetToken());

                var seatsVM = seats.Select(s => _mapper.Map<EventSeatViewModel>(s)).ToList();

                eventVM.Seats.AddRange(seatsVM);

                eventVM.Areas.Add(areaVM);
            }

            return View(eventVM);
        }

        [HttpPost]
        [AuthorizeRoles(Roles.User)]
        public async Task<IActionResult> PurchaseSeats(CreatePurchaseViewModel model)
        {
            var purchase = _mapper.Map<PurchaseModel>(model);

            var seats = new List<EventSeatModel>();

            foreach (var id in model.SeatIds)
            {
                var s = await _eventSeatClient.GetByIdAsync(id, TokenService.GetToken());
                seats.Add(_mapper.Map<EventSeatModel>(s));
            }

            await _purchaseClient.PurchaseAsync(purchase, TokenService.GetToken());

            return RedirectToAction(nameof(PurchaseHistory));
        }

        [HttpGet]
        [AuthorizeRoles(Roles.User)]
        public async Task<IActionResult> PurchaseHistory(
            [FromServices] ILayoutClient layoutClient,
            [FromServices] IVenueClient venueClient)
        {
            var userId = User.FindFirstValue("id");

            var purchases = await _purchaseClient.GetByUserIdAsync(userId, TokenService.GetToken());

            var models = new List<PurchaseViewModel>();

            foreach (var purchase in purchases)
            {
                var purchasedSeats = new List<PurchasedSeatViewModel>();

                foreach (var id in purchase.SeatIds)
                {
                    var seat = _mapper.Map<EventSeatViewModel>(await _eventSeatClient.GetByIdAsync(id, TokenService.GetToken()));
                    var area = _mapper.Map<EventAreaViewModel>(await _eventAreaClient.GetByIdAsync(seat.EventAreaId, TokenService.GetToken()));
                    var @event = _mapper.Map<EventViewModel>(await _eventClient.GetByIdAsync(area.EventId, TokenService.GetToken()));
                    var layout = _mapper.Map<LayoutViewModel>(await layoutClient.GetByIdAsync(@event.LayoutId, TokenService.GetToken()));
                    var venue = _mapper.Map<VenueViewModel>(await venueClient.GetByIdAsync(layout.VenueId, TokenService.GetToken()));

                    var purchasedSeatVm = new PurchasedSeatViewModel { Area = area, Seat = seat, Event = @event, Layout = layout, Venue = venue };

                    purchasedSeats.Add(purchasedSeatVm);
                }

                var purchaseVM = new PurchaseViewModel { PurchasedSeats = purchasedSeats, Price = purchase.Price };

                models.Add(purchaseVM);
            }

            return View(models);
        }
    }
}

src/TicketManagement.WebApplication/Views/Event/CreateEvent.cshtml
@using TicketManagement.WebApplication.Models.Event
@model CreateEventViewModel

<h1>@Localizer["Create event"]</h1>
<hr />

<div>
    <form asp-action="CreateEvent">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="w-25">
            <div class="form-group">
                <label asp-for="Venues" class="control-label"></label>
                <select id="venue" asp-for="Venue" asp-items="Model.Venues" class="form-select" ></select>
            </div>

            <div class="form-group">
                <label asp-for="Layouts" class="control-label"></label>
                <select id="layout" asp-for="Layout" asp-items="Model.Layouts" class="form-select" ></select>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="StartDate" class="form-label"></label>
                <div class="input-group" id="datetimepicker1" data-td-target-input="nearest" data-td-target-toggle="nearest">
                    <input asp-for="StartDate" value="@DateTime.Now" id="datetimepicker1Input" type="text" class="form-control" data-td-target="#datetimepicker1" />
                    <span class="input-group-text" data-td-target="#datetimepicker1" data-td-toggle="datetimepicker">
                    <span class='fa-solid fa-calendar'></span>
                    </span>
                </div>
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EndDate" class="form-label"></label>
                <div class="input-group" id="datetimepicker2" data-td-target-input="nearest"  data-td-target-toggle="nearest">
                    <input asp-for="EndDate" value="@DateTime.Now" id="datetimepicker2Input" type="text" class="form-control" data-td-target="#datetimepicker2" />
                    <span class="input-group-text" data-td-target="#datetimepicker2" data-td-toggle="datetimepicker">
                    <span class='fa-solid fa-calendar'></span>
                    </span>
                </div>
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <div class="mt-2">
                <input type="submit" value="@Localizer["Submit"]" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

@section Scripts {
<script src="~/js/datepicker.js"></script>
<script>
        $(function () {
    $('#venue').change(function () {
        var id = $(this).val();
        $.ajax({
            type: 'GET',
            url: '@Url.Action("PartialLayoutList")?venueId=' + id,
            success: function (data) {
                $('#layout').replaceWith(data);
            }
        });
    });
})
        </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/TicketManagement.WebApplication/Views/Event/EditNotPublishedEvent.cshtml
@using System.Globalization
@using TicketManagement.WebApplication.Models.Event
@model EditEventViewModel

<h1>@Localizer["Edit event"]</h1>
<hr />

<div>
    <form asp-action="EditNotPublishedEvent">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="w-25">
            <div class="form-group">
                @if (Model.Event!.ImageUrl != null)
                {
                    <img src="@Model.Event!.ImageUrl.GetAbsoluteUrl(Context.Request.Host.Value)" width=300 height=300 style="object-fit: contain; object-position: left;" />
                }

                <input type="hidden" asp-for="Event!.Id" value="@Model.Event!.Id" />
                <input type="hidden" asp-for="Event!.Published" value="true" />
                <input type="hidden" asp-for="Event!.Layout" value="@Model.Event!.Layout" />
                <input type="hidden" asp-for="Event!.Name" value="@Model.Event!.Name" />
                <input type="hidden" asp-for="Event!.Description" value="@Model.Event!.Description" />
                <input type="hidden" asp-for="Event!.StartDate" value="@Model.Event!.StartDate" />
                <input type="hidden" asp-for="Event!.EndDate" value="@Model.Event!.EndDate" />
                <input type="hidden" asp-for="Event!.ImageUrl" value="@Model.Event!.ImageUrl" />

                <h5>@Html.DisplayNameFor(modelItem => @Model.Event!.Name)</h5>
                <div>@Html.DisplayFor(modelItem => @Model.Event!.Name)</div>

                <h5>@Html.DisplayNameFor(modelItem => @Model.Event!.Description)</h5>
                <div>@Html.DisplayFor(modelItem => @Model.Event!.Description)</div>

                <h5>@Html.DisplayNameFor(modelItem => @Model.Event!.StartDate)</h5>
                <p>@User.GetLocalTime(@Model.Event!.StartDate).ToString("g", CultureInfo.CurrentCulture)</p>

                <h5>@Html.DisplayNameFor(modelItem => @Model.Event!.EndDate)</h5>
                <p>@User.GetLocalTime(@Model.Event!.EndDate).ToString("g", CultureInfo.CurrentCulture)</p>
            </div>

            <div class="form-group">
                @{
                    for (var i = 0; i < Model.Areas.Count(); i++)
                    {
                        <h5>@Localizer["{0} - seat price ({1})", @Model.Areas[i].Description!, "$"]</h5>
                        <input type="hidden" asp-for="@Model.Areas[i].Id" />
                        <input asp-for="@Model.Areas[i].Price" class="price form-control" lang="en" />

                        <span asp-validation-for="@Model.Areas[i].Price" class="text-danger"></span>
                    }
                }
            </div>

            <div class="mt-2">
                <input type="submit" value="@Localizer["Submit"]" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>
@section scripts{
<script>
        $('.price').mask("##.00", {
      reverse: true
    });

</script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/TicketManagement.WebApplication/Views/Event/Index.cshtml
@using System.Security.Claims
@using TicketManagement.WebApplication.Extensions
@using TicketManagement.WebApplication.Models.Event
@model List<EventViewModel>

<h1>@Localizer["List of events"]</h1>

@if (@User.IsEventManager())
{
    <a class="btn btn-success" asp-controller="Event" asp-action="CreateEvent">@Localizer["Create event"]</a>
}

<partial name="_EventList" model="@Model" />

src/TicketManagement.WebApplication/Views/Event/NotPublishedEvents.cshtml
@using System.Security.Claims
@using TicketManagement.WebApplication.Extensions
@using TicketManagement.WebApplication.Models.Event
@model List<EventViewModel>

<h1>@Localizer["Not published events"]</h1>

<partial name="_EventList" model="@Model" />

src/TicketManagement.WebApplication/Views/Event/PartialLayoutList.cshtml
@using TicketManagement.WebApplication.Models.Event
@model IEnumerable<LayoutViewModel>

<select id="layout" name="Layout" class="form-select">
    @foreach (var item in Model)
    {
        <option value=@item.Id>@item.Description</option>
    }
</select>

src/TicketManagement.WebApplication/Views/Event/_EventList.cshtml
@using System.Globalization
@using TicketManagement.WebApplication.Models.Event
@model IEnumerable<EventViewModel>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            @if (User.IsEventManager())
            {
                <th>
                    @Html.DisplayNameFor(model => model.Published)
                </th>
            }
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @User.GetLocalTime(@item.StartDate).ToString("g", CultureInfo.CurrentCulture)
                </td>
                <td>
                    @User.GetLocalTime(@item.EndDate).ToString("g", CultureInfo.CurrentCulture)
                </td>
                @if (User.IsEventManager())
                {
                    <th>
                        @Html.DisplayFor(modelItem => item.Published)
                    </th>
                }
                <td>
                    <a class="btn btn-success" asp-controller="Purchase" asp-action="PurchaseSeats" asp-route-id="@item.Id">@Localizer["Details"]</a>

                    @if (User.IsEventManager())
                    {
                        var modalId = "modal" + item.Id;
                        <a class="btn btn-primary" asp-action="EditEvent" asp-route-id="@item.Id">@Localizer["Edit"]</a>

                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#@modalId">@Localizer["Delete"]</button>

                        <div class="modal fade" id="@modalId" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">@Localizer["Delete confirmation"]</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="@Localizer["Close"]"></button>
                                    </div>
                                    <div class="modal-body">
                                     @Localizer["Are you sure you want to delete this event?"]
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">@Localizer["Close"]</button>
                                        <form asp-action="Delete">

                                        <input type="hidden" name="id" value="@item.Id" />

                                        <input type="submit" class="btn btn-danger" asp-action="DeleteEvent" value="@Localizer["Delete"]" />

                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>