src/TicketManagement.WebApplication/Models/VenueManagement/AreaViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TicketManagement.WebApplication.Models.VenueManagement
{
    public class AreaViewModel
    {
        public int Id { get; set; }

        public int LayoutId { get; set; }

        [Required(ErrorMessage = "Description is required")]
        [Display(Name = "Description")]
        public string? Description { get; set; }

        [Required(ErrorMessage = "Coordinate X is required")]
        [Display(Name = "Coordinate X")]
        public int CoordX { get; set; }

        [Required(ErrorMessage = "Coordinate Y is required")]
        [Display(Name = "Coordinate Y")]
        public int CoordY { get; set; }

        public List<SeatViewModel> Seats { get; set; } = new List<SeatViewModel>();
    }
}

src/TicketManagement.WebApplication/Controllers/AreaController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TicketManagement.Core.Clients.VenueApi;
using TicketManagement.Core.Clients.VenueApi.Models;
using TicketManagement.Core.Models;
using TicketManagement.WebApplication.Models.VenueManagement;
using TicketManagement.WebApplication.Services;

namespace TicketManagement.WebApplication.Controllers
{
    [AuthorizeRoles(Roles.VenueManager)]
    public class AreaController : BaseController
    {
        private readonly IAreaClient _areaClient;
        private readonly ILayoutClient _layoutClient;
        private readonly ISeatClient _seatClient;
        private readonly IMapper _mapper;

        public AreaController(
            IAreaClient areaClient,
            ILayoutClient layoutClient,
            ISeatClient seatClient,
            ITokenService tokenService,
            IMapper mapper)
            : base(tokenService)
        {
            _areaClient = areaClient ?? throw new ArgumentNullException(nameof(areaClient));
            _layoutClient = layoutClient ?? throw new ArgumentNullException(nameof(layoutClient));
            _seatClient = seatClient ?? throw new ArgumentNullException(nameof(seatClient));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        public async Task<IActionResult> AreaList(int layoutId)
        {
            var areas = await _layoutClient.GetAreasByLayoutIdAsync(layoutId, TokenService.GetToken());

            var areasVM = new List<AreaViewModel>();

            foreach (var area in areas)
            {
                var seats = await _areaClient.GetSeatsByAreaIdAsync(area.Id, TokenService.GetToken());

                var seatsVM = seats.Select(a => _mapper.Map<SeatViewModel>(a)).ToList();

                var areaVM = area.CreateVM(seatsVM);

                areasVM.Add(areaVM);
            }

            ViewBag.LayoutId = layoutId;

            return View(areasVM);
        }

        [HttpGet]
        public IActionResult CreateArea(int layoutId)
        {
            ViewBag.LayoutId = layoutId;

            return View(new AreaViewModel { LayoutId = layoutId });
        }

        [HttpPost]
        public async Task<IActionResult> CreateArea(AreaViewModel model)
        {
            var area = _mapper.Map<AreaModel>(model);

            await _areaClient.CreateAsync(area, TokenService.GetToken());

            return RedirectToAction(nameof(AreaList), new { layoutId = area.LayoutId });
        }

        [HttpGet]
        public async Task<IActionResult> EditArea(int id)
        {
            var area = await _areaClient.GetByIdAsync(id, TokenService.GetToken());

            var model = _mapper.Map<AreaViewModel>(area);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditArea(AreaViewModel model)
        {
            var area = _mapper.Map<AreaModel>(model);

            await _areaClient.UpdateAsync(area, TokenService.GetToken());

            return RedirectToAction(nameof(AreaList), new { layoutId = area.LayoutId });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteArea(int id)
        {
            var area = await _areaClient.GetByIdAsync(id, TokenService.GetToken());

            await _areaClient.DeleteAsync(id, TokenService.GetToken());

            return RedirectToAction(nameof(AreaList), new { layoutId = area.LayoutId });
        }
    }
}

src/TicketManagement.WebApplication/Controllers/SeatController.cs
using Microsoft.AspNetCore.Mvc;
using TicketManagement.Core.Clients.VenueApi;
using TicketManagement.Core.Clients.VenueApi.Models;
using TicketManagement.Core.Models;
using TicketManagement.WebApplication.Models.VenueManagement;
using TicketManagement.WebApplication.Services;

namespace TicketManagement.WebApplication.Controllers
{
    [AuthorizeRoles(Roles.VenueManager)]
    public class SeatController : BaseController
    {
        private readonly ISeatClient _seatClient;
        private readonly IAreaClient _areaClient;

        public SeatController(
            ISeatClient seatClient,
            IAreaClient areaClient,
            ITokenService tokenService)
            : base(tokenService)
        {
            _seatClient = seatClient ?? throw new ArgumentNullException(nameof(seatClient));
            _areaClient = areaClient ?? throw new ArgumentNullException(nameof(areaClient));
        }

        [HttpGet]
        public IActionResult AddSeatRow(int areaId, int row)
        {
            return View(new SeatRowViewModel { AreaId = areaId, Row = row });
        }

        [HttpPost]
        public async Task<IActionResult> AddSeatRow(SeatRowViewModel model)
        {
            for (int i = 1; i <= model.Length; i++)
            {
                var seat = new SeatModel { AreaId = model.AreaId, Row = model.Row, Number = i };

                await _seatClient.CreateAsync(seat, TokenService.GetToken());
            }

            var area = await _areaClient.GetByIdAsync(model.AreaId, TokenService.GetToken());

            return RedirectToAction(
                nameof(AreaController.AreaList),
                TrimController(nameof(AreaController)),
                new { layoutId = area.LayoutId });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSeatRow(int areaId, int row)
        {
            var seats = await _areaClient.GetSeatsByAreaIdAsync(areaId, TokenService.GetToken());

            var seatsToDelete = seats.Where(s => s.Row == row);

            foreach (var seat in seatsToDelete)
            {
                await _seatClient.DeleteAsync(seat.Id, TokenService.GetToken());
            }

            var area = await _areaClient.GetByIdAsync(areaId, TokenService.GetToken());

            return RedirectToAction(
                nameof(AreaController.AreaList),
                TrimController(nameof(AreaController)),
                new { layoutId = area.LayoutId });
        }
    }
}

src/TicketManagement.WebApplication/Views/Area/AreaList.cshtml
@using System.Globalization
@using TicketManagement.WebApplication.Models.VenueManagement
@model IEnumerable<AreaViewModel>

<a class="btn btn-success" asp-controller="Area" asp-action="CreateArea" asp-route-layoutId="@ViewBag.LayoutId">@Localizer["Create area"]</a>

@foreach (var area in Model)
{
    <div class="card mt-2" style="width: fit-content;">
        <div class="card-body">
            <h5 class="card-title">@area.Description</h5>
            <p class="card-text">X:&nbsp;@area.CoordX</p>
            <p class="card-text">Y:&nbsp;@area.CoordY</p>
        </div>
        <ul class="list-group list-group-flush">
            @{
                var rows = area.Seats.GroupBy(s => s.Row).OrderBy(s => s.Key);
            }
            @foreach (var row in rows)
            {
                var rowModalId = "rowModal" + row.Key;
                <li class="list-group-item">
                    <div class="row">

                    
                    @foreach (var seat in row.OrderBy(s => s.Number))
                    {
                        <div class="column" style="background-color: mediumseagreen;">
                            <p class="mb-0">@seat.Number</p>
                        </div>

                    }
                    <div class="column-fit-content">
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#@rowModalId">@Localizer["Delete"]</button>
                    </div>
                    </div>
                </li>

                <div class="modal fade" id="@rowModalId" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">@Localizer["Delete confirmation"]</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="@Localizer["Close"]"></button>
                            </div>
                            <div class="modal-body">
                                @Localizer["Are you sure you want to delete this row?"]
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">@Localizer["Close"]</button>
                                <form asp-controller="Seat" asp-action="DeleteSeatRow" asp-route-areaId="@area.Id" asp-route-row="@row.Key">
                                    <input type="submit" class="btn btn-danger" value="@Localizer["Delete"]" />
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            }

            @{
                var areaModalId = "areaModal" + area.Id;
            }

            <div class="row">
                <div class="column-fit-content">
                    <a class="btn btn-success" asp-controller="Seat" asp-action="AddSeatRow" asp-route-areaId="@area.Id" asp-route-row="@(rows.Any() ? rows.Max(r => r.Key) + 1 : 1)">@Localizer["Add row"]</a>
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#@areaModalId">@Localizer["Delete"]</button>
                </div>
            </div>

            <div class="modal fade" id="@areaModalId" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">@Localizer["Delete confirmation"]</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="@Localizer["Close"]"></button>
                        </div>
                        <div class="modal-body">
                            @Localizer["Are you sure you want to delete this area?"]
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">@Localizer["Close"]</button>
                            <form asp-controller="Area" asp-action="DeleteArea" asp-route-id="@area.Id"  >
                                <input type="submit" class="btn btn-danger" value="@Localizer["Delete area"]" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </ul>
    </div>
}

src/TicketManagement.WebApplication/Views/Area/CreateArea.cshtml
@using TicketManagement.WebApplication.Models.VenueManagement
@model AreaViewModel

<h1>@Localizer["Create area"]</h1>
<hr />

<div>
    <form asp-action="CreateArea">
        <input asp-for="LayoutId" type="hidden" value="@ViewBag.LayoutId" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="w-25">
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CoordX" class="control-label"></label>
                <input asp-for="CoordX" class="form-control" />
                <span asp-validation-for="CoordX" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CoordY" class="control-label"></label>
                <input asp-for="CoordY" class="form-control" />
                <span asp-validation-for="CoordY" class="text-danger"></span>
            </div>

            <div class="mt-2">
                <input type="submit" value="@Localizer["Submit"]" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

src/TicketManagement.WebApplication/Views/Area/EditArea.cshtml
@using TicketManagement.WebApplication.Models.VenueManagement
@model AreaViewModel

<h1>@Localizer["Edit area"]</h1>
<hr />

<div>
    <form asp-action="EditVenue">
        <input asp-for="Id" type="hidden" value="@Model.Id" />
        <input asp-for="LayoutId" type="hidden" value="@Model.LayoutId" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="w-25">
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" value="@Model.Description" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CoordX" class="control-label"></label>
                <input asp-for="CoordX" class="form-control" value="@Model.CoordX" />
                <span asp-validation-for="CoordX" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CoordY" class="control-label"></label>
                <input asp-for="CoordY" class="form-control" value="@Model.CoordY" />
                <span asp-validation-for="CoordY" class="text-danger"></span>
            </div>

            <div class="mt-2">
                <input type="submit" value="@Localizer["Submit"]" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>