src/TicketManagement.WebApplication/Models/Event/VenueViewModel.cs
namespace TicketManagement.WebApplication.Models.Event
{
    public class VenueViewModel
    {
        public int Id { get; set; }

        public string? Description { get; set; }

        public string? Address { get; set; }

        public string? Phone { get; set; }
    }
}

src/TicketManagement.WebApplication/Models/VenueManagement/VenueViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TicketManagement.WebApplication.Models.VenueManagement
{
    public class VenueViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Description is required")]
        [Display(Name = "Description")]
        public string? Description { get; set; }

        [Required(ErrorMessage = "Address is required")]
        [Display(Name = "Address")]
        public string? Address { get; set; }

        [Required(ErrorMessage = "Phone is required")]
        [Display(Name = "Phone")]
        public string? Phone { get; set; }

        public List<LayoutViewModel> Layouts { get; set; } = new List<LayoutViewModel>();
    }
}

src/TicketManagement.WebApplication/Controllers/LayoutController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TicketManagement.Core.Clients.VenueApi;
using TicketManagement.Core.Clients.VenueApi.Models;
using TicketManagement.Core.Models;
using TicketManagement.WebApplication.Models.VenueManagement;
using TicketManagement.WebApplication.Services;

namespace TicketManagement.WebApplication.Controllers
{
    [AuthorizeRoles(Roles.VenueManager)]
    public class LayoutController : BaseController
    {
        private readonly ILayoutClient _layoutClient;
        private readonly IMapper _mapper;

        public LayoutController(
            ILayoutClient layoutClient,
            ITokenService tokenService,
            IMapper mapper)
            : base(tokenService)
        {
            _layoutClient = layoutClient ?? throw new ArgumentNullException(nameof(layoutClient));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        public IActionResult CreateLayout(int venueId)
        {
            return View(new LayoutViewModel { VenueId = venueId });
        }

        [HttpPost]
        public async Task<IActionResult> CreateLayout(LayoutViewModel model)
        {
            var layout = _mapper.Map<LayoutModel>(model);

            await _layoutClient.CreateAsync(layout, TokenService.GetToken());

            return RedirectToAction(nameof(VenueController.VenueList), TrimController(nameof(VenueController)));
        }

        [HttpGet]
        public async Task<IActionResult> EditLayout(int id)
        {
            var layout = await _layoutClient.GetByIdAsync(id, TokenService.GetToken());

            var model = _mapper.Map<LayoutViewModel>(layout);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditLayout(LayoutViewModel model)
        {
            var layout = _mapper.Map<LayoutModel>(model);

            await _layoutClient.UpdateAsync(layout, TokenService.GetToken());

            return RedirectToAction(nameof(VenueController.VenueList), TrimController(nameof(VenueController)));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteLayout(int id)
        {
            await _layoutClient.DeleteAsync(id, TokenService.GetToken());

            return RedirectToAction(nameof(VenueController.VenueList), TrimController(nameof(VenueController)));
        }
    }
}

src/TicketManagement.WebApplication/Controllers/VenueController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TicketManagement.Core.Clients.VenueApi;
using TicketManagement.Core.Clients.VenueApi.Models;
using TicketManagement.Core.Models;
using TicketManagement.WebApplication.Models.VenueManagement;
using TicketManagement.WebApplication.Services;

namespace TicketManagement.WebApplication.Controllers
{
    [AuthorizeRoles(Roles.VenueManager)]
    public class VenueController : BaseController
    {
        private readonly IVenueClient _venueClient;
        private readonly IMapper _mapper;

        public VenueController(
            IVenueClient venueClient,
            ITokenService tokenService,
            IMapper mapper)
            : base(tokenService)
        {
            _venueClient = venueClient ?? throw new ArgumentNullException(nameof(venueClient));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        public async Task<IActionResult> VenueList()
        {
            var venues = await _venueClient.GetAllAsync(TokenService.GetToken());

            var venuesVM = new List<VenueViewModel>();

            foreach (var venue in venues)
            {
                var layouts = await _venueClient.GetLayoutsByVenueIdAsync(venue.Id, TokenService.GetToken());

                var layoutsVM = layouts.Select(layout => _mapper.Map<LayoutViewModel>(layout)).ToList();

                var venueVM = venue.CreateVM(layoutsVM);

                venuesVM.Add(venueVM);
            }

            return View(venuesVM);
        }

        [HttpGet]
        public IActionResult CreateVenue()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateVenue(VenueViewModel model)
        {
            var venue = _mapper.Map<VenueModel>(model);

            await _venueClient.CreateAsync(venue, TokenService.GetToken());

            return RedirectToAction(nameof(VenueList));
        }

        [HttpGet]
        public async Task<IActionResult> EditVenue(int id)
        {
            var venue = await _venueClient.GetByIdAsync(id, TokenService.GetToken());

            var model = _mapper.Map<VenueViewModel>(venue);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditVenue(VenueViewModel model)
        {
            var venue = _mapper.Map<VenueModel>(model);

            await _venueClient.UpdateAsync(venue, TokenService.GetToken());

            return RedirectToAction(nameof(VenueList));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteVenue(int id)
        {
            await _venueClient.DeleteAsync(id, TokenService.GetToken());

            return RedirectToAction(nameof(VenueList));
        }
    }
}

src/TicketManagement.WebApplication/Views/Venue/CreateVenue.cshtml
@using TicketManagement.WebApplication.Models.VenueManagement
@model VenueViewModel

<h1>@Localizer["Create venue"]</h1>
<hr />

<div>
    <form asp-action="CreateVenue">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="w-25">
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>

            <div class="mt-2">
                <input type="submit" value="@Localizer["Submit"]" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

src/TicketManagement.WebApplication/Views/Venue/EditVenue.cshtml
@using TicketManagement.WebApplication.Models.VenueManagement
@model VenueViewModel

<h1>@Localizer["Edit venue"]</h1>
<hr />

<div>
    <form asp-action="EditVenue">
        <input asp-for="Id" type="hidden" value="@Model.Id" />

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="w-25">
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" value="@Model.Description" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" value="@Model.Address" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" value="@Model.Phone" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>

            <div class="mt-2">
                <input type="submit" value="@Localizer["Submit"]" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

src/TicketManagement.WebApplication/Views/Venue/VenueList.cshtml
@using System.Globalization
@using TicketManagement.WebApplication.Models.VenueManagement
@model IEnumerable<VenueViewModel>

<a class="btn btn-success" asp-controller="Venue" asp-action="CreateVenue">@Localizer["Create venue"]</a>

@foreach (var venue in Model)
{
    <div class="card mt-2" style="width: fit-content;">
        <div class="card-body">
            <h5 class="card-title">@venue.Description</h5>
            <p class="card-text">@venue.Address</p>
            <p class="card-text">@venue.Phone</p>
        </div>
        <ul class="list-group list-group-flush">
            @foreach (var layout in venue.Layouts)
            {
                var layoutModalId = "layoutModal" + layout.Id;

                <li class="list-group-item">
                    <div class="row">
                        <div class="column-fit-content">
                            <p style="color: black;">@layout.Description</p>
                        </div>
                        <div class="column-fit-content">
                            <a class="btn btn-primary" asp-controller="Layout" asp-action="EditLayout" asp-route-id="@layout.Id">@Localizer["Edit"]</a>
                        </div>
                        <div class="column-fit-content">
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#@layoutModalId">@Localizer["Delete"]</button>
                        </div>
                    </div>

                </li>

                <div class="modal fade" id="@layoutModalId" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">@Localizer["Delete confirmation"]</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="@Localizer["Close"]"></button>
                            </div>
                            <div class="modal-body">
                                @Localizer["Are you sure you want to delete this layout?"]
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">@Localizer["Close"]</button>
                                <form asp-controller="Layout" asp-action="DeleteLayout" asp-route-id="@layout.Id">

                                    <input type="hidden" name="id" value="@layout.Id" />

                                    <input type="submit" class="btn btn-danger" value="@Localizer["Delete"]" />

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </ul>
        <div class="card-body">
            <a class="btn btn-success" asp-controller="Layout" asp-action="CreateLayout" asp-route-venueId="@venue.Id">@Localizer["Add layout"]</a>
            <a class="btn btn-primary" asp-controller="Venue" asp-action="EditVenue" asp-route-id="@venue.Id">@Localizer["Edit"]</a>

            @{
                var venueModalId = "venueModal" + venue.Id;
            }

            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#@venueModalId">@Localizer["Delete"]</button>

            <div class="modal fade" id="@venueModalId" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">@Localizer["Delete confirmation"]</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="@Localizer["Close"]"></button>
                        </div>
                        <div class="modal-body">
                            @Localizer["Are you sure you want to delete this venue?"]
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">@Localizer["Close"]</button>
                            <form asp-controller="Venue" asp-action="DeleteVenue" asp-route-id="@venue.Id"  >

                                <input type="hidden" name="id" value="@venue.Id" />

                                <input type="submit" class="btn btn-danger" value="@Localizer["Delete"]" />

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}